/* Generated file: node data-scripts/find-all-components.js */

import PrimaryNav from './components/PrimaryNav.vue'
import SidebarNav from './components/SidebarNav.vue'
import StoryTeller from './components/toys/StoryTeller.vue'
import Checkmark from './components/ui/Checkmark.vue'
import Collapsed from './components/ui/Collapsed.vue'
import ColumnLayout from './components/ui/ColumnLayout.vue'
import GridFill from './components/ui/GridFill.vue'
import HorizontalTileGrid from './components/ui/HorizontalTileGrid.vue'
import Icon from './components/ui/Icon.vue'
import IconButton from './components/ui/IconButton.vue'
import PanAndZoom from './components/ui/PanAndZoom.vue'
import Property from './components/ui/Property.vue'
import PropertyPanel from './components/ui/PropertyPanel.vue'
import Tabulation from './components/ui/Tabulation.vue'
import TechBox from './components/ui/TechBox.vue'
import TechDiagram from './components/ui/TechDiagram.vue'
import TechEdge from './components/ui/TechEdge.vue'
import Toggle from './components/ui/Toggle.vue'
import VerticalTileGrid from './components/ui/VerticalTileGrid.vue'
import FullPageSection from './views/FullPageSection.vue'
import Home from './views/Home.vue'
import MultiPageSectionView from './views/multi-page-section/MultiPageSectionView.vue'
import Section1 from './views/multi-page-section/Section1.vue'
import Section2 from './views/multi-page-section/Section2.vue'
import Section3 from './views/multi-page-section/Section3.vue'
import MultiPageSectionNav from './views/multi-page-section/ui/MultiPageSectionNav.vue'
import SaveFileManagement from './views/SaveFileManagement.vue'
import ComponentTests from './views/settings/debug/ComponentTests.vue'
import Debug from './views/settings/debug/Debug.vue'
import Icons from './views/settings/debug/Icons.vue'
import Gamedata from './views/settings/Gamedata.vue'
import Mods from './views/settings/Mods.vue'
import Settings from './views/settings/Settings.vue'
import SettingsNav from './views/settings/ui/SettingsNav.vue'
import StartNewGame from './views/StartNewGame.vue'
import Template from './views/Template.vue'

export default {
  PrimaryNav, SidebarNav, StoryTeller, Checkmark, Collapsed, ColumnLayout, GridFill, HorizontalTileGrid, Icon, IconButton, PanAndZoom, Property, PropertyPanel, Tabulation, TechBox, TechDiagram, TechEdge, Toggle, VerticalTileGrid, FullPageSection, Home, MultiPageSectionView, Section1, Section2, Section3, MultiPageSectionNav, SaveFileManagement, ComponentTests, Debug, Icons, Gamedata, Mods, Settings, SettingsNav, StartNewGame, Template
}
